/**
 * Deterministic Mock AI Adapter (Phase 12 — docs/AI_ARCHITECTURE.md).
 * Enables end-to-end testing, local benchmarking, and sandboxed AI workflow execution.
 */
import type { AiModelAdapter, AiModelCallParams, AiModelCallResult } from "./types";

export class MockAdapter implements AiModelAdapter {
  public readonly providerType = "MOCK";

  public async generateText(params: AiModelCallParams): Promise<AiModelCallResult> {
    const start = Date.now();
    const prompt = params.prompt.trim();

    // Generate intelligent simulation text matching intent
    let responseText = "";
    if (params.responseMimeType === "application/json" || prompt.toLowerCase().includes("json")) {
      responseText = JSON.stringify({
        status: "success",
        synthesis: "Simulated structured intelligence output generated by Artify Mock Adapter.",
        entities: [{ name: "Target Entity", type: "ENTERPRISE", score: 0.94 }],
        recommendation: "Proceed with executive relationship advancement.",
        timestamp: new Date().toISOString(),
      }, null, 2);
    } else if (prompt.toLowerCase().includes("summariz") || prompt.toLowerCase().includes("brief")) {
      responseText = `**Executive Brief**\n\n- **Overview:** Synthesized analysis for prompt: "${prompt.slice(0, 80)}..."\n- **Key Finding:** Strong commercial alignment observed across account parameters.\n- **Risk Factor:** Low risk with operational governance active.\n- **Recommended Next Step:** Schedule milestone audit and confirm contract schedule.`;
    } else if (prompt.toLowerCase().includes("classif") || prompt.toLowerCase().includes("categor")) {
      responseText = `**Classification Result**\n- Primary Category: HIGH_PRIORITY\n- Confidence Score: 0.92\n- Strategic Alignment: Enterprise Tier Growth`;
    } else {
      responseText = `Artify Intelligence Response:\n\nAnalysis completed successfully for model ${params.modelName}.\n\nParameters evaluated: temperature=${params.temperature ?? 0.3}, maxTokens=${params.maxTokens ?? 2048}.\nSystem instructions observed: ${params.systemInstruction ? "Active" : "None"}.\n\nEvaluated input: ${prompt}\n\nOutput: High quality deterministic synthesis conforming to Artify enterprise governance policies.`;
    }

    const durationMs = Math.max(15, Date.now() - start);
    const inputTokens = Math.max(1, Math.ceil(prompt.length / 4));
    const outputTokens = Math.max(1, Math.ceil(responseText.length / 4));

    return {
      text: responseText,
      inputTokens,
      outputTokens,
      totalTokens: inputTokens + outputTokens,
      durationMs,
      finishReason: "STOP",
    };
  }

  public async generateStructured<T = unknown>(params: AiModelCallParams): Promise<T> {
    const res = await this.generateText({
      ...params,
      responseMimeType: "application/json",
    });
    return JSON.parse(res.text) as T;
  }

  public async generateEmbedding(params: { text: string; modelName?: string; dimension?: number }): Promise<number[]> {
    const dim = params.dimension || 768;
    const text = params.text.toLowerCase();
    const vec = new Array(dim).fill(0);
    // Deterministic semantic-like hash simulation for unit & integration testing
    for (let i = 0; i < text.length; i++) {
      const code = text.charCodeAt(i);
      const idx = (code * 31 + i * 17) % dim;
      vec[idx] = (vec[idx] + (code / 255.0)) % 1.0;
    }
    // Normalize vector to unit length
    const norm = Math.sqrt(vec.reduce((sum, v) => sum + v * v, 0)) || 1;
    return vec.map((v) => Number((v / norm).toFixed(6)));
  }
}
